name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^0.13.5
  intl: ^0.18.0
  shared_preferences: ^2.2.0
  pdf: ^3.10.4
  path_provider: ^2.1.2 

flutter:
  uses-material-design: true
