# Generated by Django 5.1 on 2025-03-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('tea_count', models.IntegerField(default=0)),
                ('coffee_count', models.IntegerField(default=0)),
                ('snacks_count', models.IntegerField(default=0)),
                ('total_amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20, unique=True)),
                ('total_tea', models.IntegerField(default=0)),
                ('total_coffee', models.IntegerField(default=0)),
                ('total_snacks', models.IntegerField(default=0)),
                ('total_expense', models.FloatField(default=0.0)),
            ],
        ),
    ]
