# Generated by Django 5.1 on 2025-03-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_dailyexpense_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='dailyexpense',
            name='other_items',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='monthlyexpense',
            name='other_items',
            field=models.JSONField(default=dict),
        ),
    ]
