# Generated by Django 5.1 on 2025-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_menuitem_dailyexpense_other_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyexpense',
            old_name='other_items',
            new_name='items',
        ),
        migrations.RenameField(
            model_name='monthlyexpense',
            old_name='other_items',
            new_name='items',
        ),
        migrations.RemoveField(
            model_name='dailyexpense',
            name='coffee_count',
        ),
        migrations.RemoveField(
            model_name='dailyexpense',
            name='snacks_count',
        ),
        migrations.RemoveField(
            model_name='dailyexpense',
            name='tea_count',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='total_coffee',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='total_snacks',
        ),
        migrations.RemoveField(
            model_name='monthlyexpense',
            name='total_tea',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.FloatField(),
        ),
    ]
