# Generated by Django 5.1 on 2025-03-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_rename_other_items_dailyexpense_items_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('item', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
