# Generated by Django 5.1 on 2025-03-20 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
